apiVersion: v1
kind: Pod
metadata:
  name: privileged-compliant-pod
spec:
  securityContext:
    runAsUser: 0
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      privileged: true
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo